import Link from 'next/link';
import { FcGoogle } from 'react-icons/fc';
import { HiArrowUpRight, HiCheckBadge, HiStar, HiUserGroup } from 'react-icons/hi2';
import { Locale, localizedPath } from '@/lib/i18n';
import { getPrimaryServices } from '@/lib/services';
import ProjectImage from './ProjectImage';
import site from '../../config/site.json';
import reviews from '../../config/reviews.json';
import { JsonLd, businessData } from '@/lib/metadata';

const copy = {
  en: { eyebrow: 'YOUR PROPERTY, OUR PROFESSION', title: 'Entretien Domestique', city: 'Montréal.', intro: 'Window Cleaning, Gutter Cleaning, Dryer Vent Cleaning, Pressure Washing and Deck Staining. Professional home maintenance, with attention to details.', quote: 'Get your free quote', explore: 'Explore our services', location: 'Montréal · West Island · Laval · South Shore', insured: 'Fully insured', insuredNote: 'Care for your property, peace of mind for you.', owner: 'Owner-operated', ownerNote: 'A personal approach, from start to finish.', google: '5-star Google reviews', googleNote: 'Recommended by your neighbours.', services: 'WHAT WE DO', servicesTitle: 'Our Services', servicesIntro: 'Safe and professional maintenance for your property.', learn: 'Explore service', reviews: 'WORDS FROM OUR CUSTOMERS', reviewsTitle: 'Customer Testimonials', reviewsIntro: 'Real experiences from people who trust us with their homes.', googleLink: 'Read our Google reviews', quoteEyebrow: 'LET’S GET STARTED', quoteTitle: 'Your next project starts with a conversation.', quoteText: 'Tell us what your home needs. We’ll help you take the next step with a free, no-obligation quote.', call: 'Or call', translation: '' },
  fr: { eyebrow: 'VOTRE PROPRIÉTÉ, NOTRE MÉTIER', title: 'Entretien Domestique', city: 'Montréal.', intro: 'Lavage de vitres, nettoyage de gouttières et de conduits de sécheuse, lavage à pression et teinture de terrasses. Un entretien professionnel, avec le souci du détail.', quote: 'Obtenir une soumission gratuite', explore: 'Découvrir nos services', location: 'Montréal · Ouest-de-l’Île · Laval · Rive-Sud', insured: 'Entièrement assurés', insuredNote: 'Votre maison entre bonnes mains.', owner: 'Propriétaires sur le terrain', ownerNote: 'Un service personnalisé, du début à la fin.', google: 'Avis Google 5 étoiles', googleNote: 'Recommandés par vos voisins.', services: 'NOS SERVICES', servicesTitle: 'Nos services', servicesIntro: 'Un entretien professionnel et sécuritaire pour votre propriété.', learn: 'Découvrir le service', reviews: 'CE QUE DISENT NOS CLIENTS', reviewsTitle: 'Témoignages de nos clients', reviewsIntro: 'Des clients vous racontent leur expérience avec nous.', googleLink: 'Lire nos avis Google', quoteEyebrow: 'PARLONS DE VOTRE PROJET', quoteTitle: 'Votre prochain projet commence par une conversation.', quoteText: 'Dites-nous ce qu’il vous faut. On vous aide à planifier la suite avec une soumission gratuite, sans obligation.', call: 'Ou appelez le', translation: 'Traduit de l’anglais' },
};
const testimonials = [
  { ...reviews[0], url: site.contact.googleMapsUrl },
  { author: 'Suzan', rating: 5, url: 'https://maps.app.goo.gl/xiacAadWv2PYdd2b6', text: 'Dealing with Chris and Blair was a total pleasure. Everything about them was very professional and the quality of their work second to none. We would not hesitate to recommend them.' },
  { author: 'Valerie', rating: 5, url: 'https://maps.app.goo.gl/qJUWP2jnppWwg7NKA', text: 'It is rare to find young professionals who take such pride in their work and deliver this level of service. My husband and I would not hesitate for a second to recommend these fine young men and their company. Excellent experience from start to finish.' },
];
const translatedReviews = [
  'Chris et Blair ont fait un excellent travail pour nettoyer les gouttières, les soffites, le revêtement, les fenêtres et les clôtures. C’est un plaisir de faire affaire avec eux, et je recommande leurs services sans hésiter.',
  'Ça a été un vrai plaisir de faire affaire avec Chris et Blair. Ils ont été très professionnels du début à la fin, et la qualité de leur travail était exceptionnelle. On les recommande sans hésiter.',
  'C’est rare de voir de jeunes professionnels aussi fiers de leur travail et qui offrent un service de cette qualité. Mon mari et moi recommandons ces jeunes hommes et leur entreprise sans hésiter une seconde. Une excellente expérience du début à la fin.',
];
const cardPhotos: Record<string, string> = { 'gutter-cleaning': '/images/services/gutter-cleaning.png', 'window-cleaning': '/images/services/window-cleaning-header.png', 'pressure-washing': '/images/services/pressure-washing.png', 'deck-staining': '/images/services/deckstaining1.png' };

export default function HomePage({ locale }: { locale: Locale }) {
  const c = copy[locale];
  return <>
    <JsonLd data={businessData()} />
    <section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span />{c.eyebrow}</p><h1>{c.title}<br /><em>{c.city}</em></h1><p className="hero-intro">{c.intro}</p><div className="hero-buttons"><Link className="button button-primary" href={localizedPath(locale, '/contact')} data-track-event="quote_cta_click" data-track-placement="home-hero">{c.quote}<HiArrowUpRight aria-hidden="true" /></Link><a className="text-link" href="#services">{c.explore}<span aria-hidden="true">↓</span></a></div><p className="hero-location">{c.location}</p></div><div className="hero-photo-wrap"><ProjectImage src="/images/frontpagesplash.png" alt={locale === 'en' ? 'EDMTL window cleaner at work on a Montréal home' : 'Laveur de vitres EDMTL au travail sur une maison à Montréal'} className="hero-photo" priority sizes="(min-width: 1200px) 570px, (min-width: 900px) 48vw, 100vw" /><div className="hero-photo-note"><span>{locale === 'en' ? '“Fantastic service. Nice people.”' : '« Excellent service. Des gens sympathiques. »'}</span><a className="hero-review-author" href="https://maps.app.goo.gl/GUFpbtGATFsMrWT46" target="_blank" rel="noopener noreferrer" aria-label={locale === 'en' ? 'Read Gordon’s review on Google' : 'Lire l’avis de Gordon sur Google'}><span>— Gordon</span><span aria-hidden="true">·</span><FcGoogle aria-hidden="true" /></a>{locale === 'fr' && <small>{c.translation}</small>}</div></div></div></section>
    <section className="trust-strip" aria-label={locale === 'en' ? 'Why choose EDMTL' : 'Pourquoi choisir EDMTL'}><div className="container trust-grid">{[{ icon: HiCheckBadge, title: c.insured, note: c.insuredNote }, { icon: HiUserGroup, title: c.owner, note: c.ownerNote }, { icon: HiStar, title: c.google, note: c.googleNote }].map(item => <div className="trust-item" key={item.title}><item.icon aria-hidden="true" /><div><strong>{item.title}</strong><p>{item.note}</p></div></div>)}</div></section>
    <section id="services" className="section services-section"><div className="container"><div className="section-heading"><div><h2>{c.servicesTitle}</h2></div><p>{c.servicesIntro}</p></div><div className="primary-services">{getPrimaryServices(locale).map((service) => <Link key={service.slug} className="service-card" href={localizedPath(locale, `/services/${service.slug}`)} data-track-event="select_service" data-track-service={service.slug} data-track-placement="home-service-grid"><div className="service-card-image"><ProjectImage src={cardPhotos[service.slug] ?? service.hero} alt={service.title} sizes="(min-width: 1200px) 370px, (min-width: 900px) 30vw, (min-width: 640px) 46vw, 100vw" /></div><div className="service-card-copy"><h3>{service.title}</h3><p>{service.description}</p><span className="card-link">{c.learn}<HiArrowUpRight aria-hidden="true" /></span></div></Link>)}</div></div></section>
    <section id="reviews" className="section reviews-section"><div className="container"><div className="section-heading"><div><h2>{c.reviewsTitle}</h2></div><p>{c.reviewsIntro}</p></div><div className="review-grid">{testimonials.map((review, index) => <article className="review-card" key={review.author}>{review.rating === 5 && <div className="review-stars" aria-label={locale === 'en' ? '5 out of 5 stars' : '5 étoiles sur 5'}>★★★★★</div>}<blockquote><p>“{locale === 'fr' ? translatedReviews[index] : review.text}”</p></blockquote><div className="review-author"><span aria-hidden="true">{review.author.slice(0, 1)}</span><div><strong>{review.author}</strong>{review.rating === 5 && <a href={review.url} target="_blank" rel="noopener noreferrer"><small>Google ↗</small></a>}</div></div>{locale === 'fr' && <details className="review-original"><summary>{c.translation} · Voir l’original</summary><p lang="en">{review.text}</p></details>}</article>)}</div><div className="reviews-link"><a className="text-link" href={site.contact.googleMapsUrl} target="_blank" rel="noopener noreferrer" data-track-event="reviews_click" data-track-placement="home-reviews">{c.googleLink}<HiArrowUpRight aria-hidden="true" /></a></div></div></section>
    <section className="section home-quote"><div className="container quote-banner"><div><p className="eyebrow">{c.quoteEyebrow}</p><h2>{c.quoteTitle}</h2><p>{c.quoteText}</p></div><div className="quote-banner-actions"><Link className="button button-primary" href={localizedPath(locale, '/contact')} data-track-event="quote_cta_click" data-track-placement="home-final">{c.quote}<HiArrowUpRight aria-hidden="true" /></Link><a href={`tel:${site.contact.phone}`}>{c.call} <strong>{site.contact.phone}</strong></a></div></div></section>
  </>;
}
