import Link from 'next/link';
import { HiArrowUpRight, HiCheckBadge, HiStar, HiUserGroup } from 'react-icons/hi2';
import { Locale, localizedPath } from '@/lib/i18n';
import { getPrimaryServices } from '@/lib/services';
import ProjectImage from './ProjectImage';
import site from '../../config/site.json';
import reviews from '../../config/reviews.json';
import { JsonLd, businessData } from '@/lib/metadata';

const copy = {
  en: { eyebrow: 'YOUR HOME. OUR KNOW-HOW.', title: 'Entretien Domestique', city: 'Montréal.', intro: 'Window cleaning, gutter cleaning, pressure washing and deck care. Professional home maintenance, with attention to the details.', quote: 'Get your free quote', explore: 'Explore our services', location: 'Montréal · West Island · Laval · South Shore', insured: 'Fully insured', insuredNote: 'Care for your home, peace of mind for you.', owner: 'Owner-operated', ownerNote: 'A personal approach, from start to finish.', google: '5-star Google reviews', googleNote: 'Recommended by your neighbours.', services: 'WHAT WE DO', servicesTitle: 'A little care goes a long way.', servicesIntro: 'Thoughtful maintenance for the places you call home.', learn: 'Explore service', reviews: 'WORDS FROM OUR CUSTOMERS', reviewsTitle: 'Good work. Happy neighbours.', reviewsIntro: 'Real experiences from people who trust us with their homes.', googleLink: 'Read our Google reviews', quoteEyebrow: 'LET’S GET STARTED', quoteTitle: 'Your next project starts with a conversation.', quoteText: 'Tell us what your home needs. We’ll help you take the next step with a free, no-obligation quote.', call: 'Or call', translation: '' },
  fr: { eyebrow: 'VOTRE MAISON. NOTRE SAVOIR-FAIRE.', title: 'Entretien Domestique', city: 'Montréal.', intro: 'Lavage de vitres, nettoyage de gouttières, lavage à pression et entretien de terrasses. Un travail professionnel, jusque dans les détails.', quote: 'Obtenir une soumission gratuite', explore: 'Découvrir nos services', location: 'Montréal · Ouest-de-l’Île · Laval · Rive-Sud', insured: 'Entièrement assurés', insuredNote: 'Votre maison entre bonnes mains.', owner: 'Propriétaires sur le terrain', ownerNote: 'Un service personnalisé, du début à la fin.', google: 'Avis Google 5 étoiles', googleNote: 'Recommandés par vos voisins.', services: 'NOS SERVICES', servicesTitle: 'Un peu d’entretien fait toute la différence.', servicesIntro: 'Des soins attentifs pour la maison qui vous ressemble.', learn: 'Découvrir le service', reviews: 'CE QUE DISENT NOS CLIENTS', reviewsTitle: 'Du bon travail. Des voisins heureux.', reviewsIntro: 'Les expériences de personnes qui nous confient leur maison.', googleLink: 'Lire nos avis Google', quoteEyebrow: 'PARLONS DE VOTRE PROJET', quoteTitle: 'Votre prochain projet commence par une conversation.', quoteText: 'Dites-nous ce dont votre maison a besoin. Nous vous aiderons à passer à la prochaine étape avec une soumission gratuite et sans engagement.', call: 'Ou appelez le', translation: 'Traduit de l’anglais' },
};
const translatedReviews = [
  'Chris et Blair ont fait un excellent travail de nettoyage des gouttières, soffites, revêtement, fenêtres et clôtures. Ils sont très agréables et je recommande leurs services avec plaisir.',
  'Après avoir été très satisfaite du lavage de vitres l’an dernier, j’ai fait laver à pression ma terrasse, mon patio et mon cabanon cette année. Je ne pourrais pas être plus heureuse. Chris et Blair sont professionnels et très minutieux. Je les recommande vivement. Notre terrasse de six ans est comme neuve.',
  'Nous avons fait appel à Chris et Blair pour le lavage de vitres et sommes très satisfaits du résultat. Ils sont sympathiques, professionnels et ont fait un excellent travail. Nous ferons encore appel à eux.',
];
const cardPhotos: Record<string, string> = { 'gutter-cleaning': '/images/services/gutter-cleaning.png', 'window-cleaning': '/images/services/window-cleaning-header.png', 'pressure-washing': '/images/services/pressure-washing.png', 'deck-staining': '/images/services/deckstaining1.png' };

export default function HomePage({ locale }: { locale: Locale }) {
  const c = copy[locale];
  return <>
    <JsonLd data={businessData()} />
    <section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span />{c.eyebrow}</p><h1>{c.title}<br /><em>{c.city}</em></h1><p className="hero-intro">{c.intro}</p><div className="hero-buttons"><Link className="button button-primary" href={localizedPath(locale, '/contact')} data-track-event="quote_cta_click" data-track-placement="home-hero">{c.quote}<HiArrowUpRight aria-hidden="true" /></Link><a className="text-link" href="#services">{c.explore}<span aria-hidden="true">↓</span></a></div><p className="hero-location">{c.location}</p></div><div className="hero-photo-wrap"><ProjectImage src="/images/frontpagesplash.png" alt={locale === 'en' ? 'EDMTL window cleaner at work on a Montréal home' : 'Laveur de vitres EDMTL au travail sur une maison à Montréal'} className="hero-photo" priority sizes="(min-width: 1200px) 570px, (min-width: 900px) 48vw, 100vw" /><div className="hero-photo-note"><span className="star-row" aria-hidden="true">★★★★★</span><span>{locale === 'en' ? 'Careful work. Every time.' : 'Le souci du travail bien fait.'}</span></div></div></div></section>
    <section className="trust-strip" aria-label={locale === 'en' ? 'Why choose EDMTL' : 'Pourquoi choisir EDMTL'}><div className="container trust-grid">{[{ icon: HiCheckBadge, title: c.insured, note: c.insuredNote }, { icon: HiUserGroup, title: c.owner, note: c.ownerNote }, { icon: HiStar, title: c.google, note: c.googleNote }].map(item => <div className="trust-item" key={item.title}><item.icon aria-hidden="true" /><div><strong>{item.title}</strong><p>{item.note}</p></div></div>)}</div></section>
    <section id="services" className="section services-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{c.services}</p><h2>{c.servicesTitle}</h2></div><p>{c.servicesIntro}</p></div><div className="primary-services">{getPrimaryServices(locale).map((service, index) => <Link key={service.slug} className="service-card" href={localizedPath(locale, `/services/${service.slug}`)} data-track-event="select_service" data-track-service={service.slug} data-track-placement="home-service-grid"><div className="service-card-image"><ProjectImage src={cardPhotos[service.slug] ?? service.hero} alt={service.title} sizes="(min-width: 1200px) 270px, (min-width: 640px) 46vw, 100vw" /><span className="card-number">0{index + 1}</span></div><div className="service-card-copy"><h3>{service.title}</h3><p>{service.description}</p><span className="card-link">{c.learn}<HiArrowUpRight aria-hidden="true" /></span></div></Link>)}</div></div></section>
    <section id="reviews" className="section reviews-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{c.reviews}</p><h2>{c.reviewsTitle}</h2></div><p>{c.reviewsIntro}</p></div><div className="review-grid">{reviews.slice(0, 3).map((review, index) => <article className="review-card" key={review.author}><div className="review-stars" aria-label={locale === 'en' ? '5 out of 5 stars' : '5 étoiles sur 5'}>★★★★★</div><blockquote><p>“{locale === 'fr' ? translatedReviews[index] : review.text}”</p></blockquote><div className="review-author"><span aria-hidden="true">{review.author.slice(0, 1)}</span><div><strong>{review.author}</strong><small>Google</small></div></div>{locale === 'fr' && <details className="review-original"><summary>{c.translation} · Voir l’original</summary><p lang="en">{review.text}</p></details>}</article>)}</div><div className="reviews-link"><a className="text-link" href={site.contact.googleMapsUrl} target="_blank" rel="noopener noreferrer" data-track-event="reviews_click" data-track-placement="home-reviews">{c.googleLink}<HiArrowUpRight aria-hidden="true" /></a></div></div></section>
    <section className="section home-quote"><div className="container quote-banner"><div><p className="eyebrow">{c.quoteEyebrow}</p><h2>{c.quoteTitle}</h2><p>{c.quoteText}</p></div><div className="quote-banner-actions"><Link className="button button-primary" href={localizedPath(locale, '/contact')} data-track-event="quote_cta_click" data-track-placement="home-final">{c.quote}<HiArrowUpRight aria-hidden="true" /></Link><a href={`tel:${site.contact.phone}`}>{c.call} <strong>{site.contact.phone}</strong></a></div></div></section>
  </>;
}
